#!/usr/bin/env python3
"""
Build the faint administrative overlay used on the Previsão regional figure:
Santa Catarina + neighbouring states (PR, SP) dissolved to their outlines.

Source: tbrugz/geodata-br (municipality polygons derived from IBGE malhas),
        github.com/tbrugz/geodata-br — CC-BY / public IBGE lineage.
Method: fetch each UF's municipalities, buffer(0) to fix rings, union -> state
        outline, simplify (~400 m) for a light context border. Written ONCE as a
        static asset (site/data/geo/estados_sul.geojson); it does not change per run,
        so it is committed and not regenerated by the daily workflow.

Run:    python scripts/build_states_overlay.py
Only needs network the one time you (re)build the file.
"""
from __future__ import annotations
import json
import urllib.request
from pathlib import Path

import geopandas as gpd
from shapely.ops import unary_union
from shapely.geometry import mapping

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "site" / "data" / "geo" / "estados_sul.geojson"
BASE = "https://raw.githubusercontent.com/tbrugz/geodata-br/master/geojson/geojs-{uf}-mun.json"
UFS = {"42": "SC", "41": "PR", "35": "SP"}   # WRF box spans SC and its northern neighbours
SIMPLIFY_DEG = 0.004                         # ~400 m — a context border, not a survey line


def main():
    feats = []
    for code, sig in UFS.items():
        req = urllib.request.Request(BASE.format(uf=code), headers={"User-Agent": "Mozilla/5.0"})
        j = json.loads(urllib.request.urlopen(req, timeout=60).read())
        g = gpd.GeoDataFrame.from_features(j["features"], crs="EPSG:4326")
        g["geometry"] = g.geometry.buffer(0)
        diss = unary_union(g.geometry.values).simplify(SIMPLIFY_DEG, preserve_topology=True)
        feats.append({"type": "Feature", "properties": {"uf": sig, "code": code},
                      "geometry": mapping(diss)})
        print(f"{sig}: {diss.geom_type}  bounds={[round(x, 2) for x in diss.bounds]}")
    fc = {"type": "FeatureCollection", "name": "estados_sul",
          "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}},
          "features": feats}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fc, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {OUT}  ({OUT.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
